# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e530b300de500c0defc982a1a81cb022ee84fe3d409602b19646150577c41dfc55412a9b634fcb6494059572d458e54c9e2dac3f0c2731806414cf1073ac55c0

test:
  secret_key_base: c0ea067f7c8e0fe06b195cb569da1b4a9ea7cb73333db20f57c12f07e399210594e4fe703b4d34997d4204b9b7027a31b565e48ae34b5b399118e94036278062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
